[package]
name = "ZenoRust"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
logos = "0.16.1"
reqwest = { version = "0.13.1", features = ["blocking", "json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
