name: zenodart
description: A Dart port of the ZenoEngine core.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.0
  args: ^2.4.0
  http: ^1.6.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  intl: ^0.20.2
  uuid: ^4.5.2
  crypto: ^3.0.7
  sqlite3: ^3.1.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0
